feat(prettier): Add prettier config package
elseu/sdu-react-scripts pull request #20
Opened 2022-09-22 10:05 UTC by BartWaardenburg

https://jirasdu.atlassian.net/browse/TDS-88

Shareable prettier config
- [ ] Default configuration with added single quotes, trailing comma's and a max length of 100 (https://prettier.io/docs/en/options.html#print-width). Print width is not the same as `eslint` `max_len`, so that's why I used 100 instead of 120 for now.
- [ ] Eslint changed by removing prettier conflicting rules and added the prettier plugin.
- [ ] The usage of editorConfig is hard since we can't share it using an npm package (https://github.com/editorconfig/editorconfig/issues/236). Luckily we don't have any specific prettier rules that should be copied by either configs. So for now we don't extend the editorConfig using prettier to prevent uncontrollable behaviour.
- [ ] Made the commit which changed the formatting a 'hidden commit' for git blame so history is not changed (https://medium.com/codex/how-to-introduce-a-code-formatter-without-messing-up-git-history-4a16bd074c10)

2022-09-22 10:16 UTC, daphnesmit commented on packages/prettier/package.json
> +          "packageName": "@elseu/sdu-react-scripts-eslint",
rename!

2022-09-22 10:20 UTC, daphnesmit commented on packages/prettier/README.md
> +  "name": "my-cool-library",
maybe use example @elseu/library-name

2022-09-22 12:05 UTC, BartWaardenburg commented
If the package from https://github.com/elseu/sdu-react-scripts/pull/21 is used this will prevent from conflict with stylelint

2022-09-22 13:22 UTC, carlobernardini commented on package.json
> +    "**/*.md": [
Should we maybe include yaml too?

2022-09-22 13:25 UTC, carlobernardini requested changes
Looks good @BartWaardenburg, just a few tiny comments

2022-09-22 13:41 UTC, BartWaardenburg commented on packages/eslint/README.md
>  ## Autoformatting on save in VSCode
👍 I also changed the section on autoformatting and moved it to the prettier package readme.

2022-09-22 13:44 UTC, carlobernardini commented on package.json
> +    "**/*.md": [
Right, my confusion. I would say we leave that up to the individual projects for starters. What do you think @daphnesmit?

2022-09-22 13:53 UTC, skarnl commented on .git-blame-ignore-revs
> +acc495407afe008f638823d296afcc1db8c13ff4
🎉

2022-09-22 13:55 UTC, skarnl approved these changes

2022-09-22 13:56 UTC, BartWaardenburg commented on .git-blame-ignore-revs
> +acc495407afe008f638823d296afcc1db8c13ff4
@skarnl Since you're the expert on this. Does squash committing this branch into develop cause this line to no longer work or does it keep the individual commit SHA's stored somewhere?

2022-09-22 14:17 UTC, skarnl commented on .git-blame-ignore-revs
> +acc495407afe008f638823d296afcc1db8c13ff4
SHA of a commit is basically a hash based on a combination of:
- content (what changed, so the actual diff) 
- who changed it (author/email/etc)
- commit message
- when was the commit done (date/time)
- what commit is the parent commit
(and probably some other stuff)

So that's when you rebase, the SHA is different (since the parent-SHA will be different etc). Or when you change or amend a commit, the diff or message or date/time are different -> different SHA.

When you change _anything_ of a commit, the SHA will be different.

2022-09-23 12:24 UTC, daphnesmit commented on package.json
> +    "**/*.md": [
i think its up to the project honestly

2022-09-23 12:25 UTC, daphnesmit approved these changes

2022-09-23 12:48 UTC, BartWaardenburg commented on .git-blame-ignore-revs
> +acc495407afe008f638823d296afcc1db8c13ff4
I did the interactive rebase and changed the ignore-revs sha 👍

2022-09-23 12:49 UTC, merged