feat: sync translations
elseu/sdu-react-scripts pull request #49
Opened 2024-01-08 15:38 UTC by michelvermeer

TODO:

- Read locales from source repository from ...  .env (?)
- Read POEDITOR_API_TOKEN and POEDITOR_PROJECT_ID from github params

2024-01-08 15:47 UTC, daphnesmit requested changes
Security

2024-01-08 15:47 UTC, daphnesmit commented on packages/sync-translations/package.json
> +    "sdu-deps": "./bin/sdu-sync-translations.js"
Ehhh

2024-01-08 15:47 UTC, daphnesmit commented on packages/sync-translations/package.json
> +    "sdu-react-scripts-update-deps": "./bin/sdu-sync-translations.js",
Wat is dit?

2024-01-08 15:47 UTC, daphnesmit commented on packages/sync-translations/src/index.ts
> +  POEDITOR_API_TOKEN: 'fccf4f817d0d7e1f9f957ea8c6d1294e',
Hardcoded in repo?

2024-01-08 15:53 UTC, michelvermeer commented on packages/sync-translations/package.json
> +    "sdu-deps": "./bin/sdu-sync-translations.js"
Sloppy copy-paste :)

2024-01-18 10:52 UTC, skarnl commented
Will close this PR - to get rid of the api-key ... I hope

2024-01-18 10:52 UTC, closed without merging